stable-diffusion-2:
  vae:
    classname: AutoencoderKL
    storage: cloud
    hub: stabilityai/stable-diffusion-2
    subfolder: vae
    train: false
  unet:
    classname: UNet2DConditionModel
    storage: local
    path: runs/run_2/unet
    train: true
  scheduler:
    classname: DDIMScheduler
    storage: cloud
    hub: stabilityai/stable-diffusion-2
    subfolder: scheduler
  tokenizer:
    classname: CLIPTokenizer
    storage: cloud
    hub: stabilityai/stable-diffusion-2
    subfolder: tokenizer
  text_encoder: 
    classname: CLIPTextModel
    storage: local
    path: runs/run_2/text_encoder
    train: true